**Section 3.3** An airline with two types of airplanes, P1 and P2, has contracted with a tour group to provide transportation for a minimum of 400 first class, 750 tourist class, and 1500 economy class passengers. For a certain trip, airplane P1 costs \\$10,000 to operate and can accommodate 20 first class, 50 tourist class, and 110 economy class passengers. Airplane P2 costs \\$8500
to operate and can accommodate 18 first class, 30 tourist class and 44 economy class passengers. How many of each type of airplane should be used in order to minimize the operating cost?

**Solution:**
Let x be the number of P1 airplanes<br>
Let x be the number of P2 airplanes<br>

Operating cost to be minimized = 10000 x + 8500 y <br>
Subject to:
* 20 x + 18 y ≥ 400  
* 50 x  + 30 y ≥ 750
* 110 x  + 44 y ≥ 1500
* x ≥ 0, y ≥ 0 <br>

In [2]:
# Set up the constraints and obtain the corner points
import numpy as np

a1 = np.array([[20,18], [50,30]])
b1 = np.array([400,750])

# solve the two sets of equations at a time to get points of intersection of the lines
c1 = np.linalg.solve(a1, b1)
print(c1)

# Second pair of corner points
a2 = np.array([[50,30], [110,44]])
b2 = np.array([750,1500])
c2 = np.linalg.solve(a2, b2)
print(c2)

# Third pair of corner points
a3 = np.array([[20,18], [110,44]])
b3 = np.array([400,1500])
c3 = np.linalg.solve(a3, b3)
print(c3)

[ 5.         16.66666667]
[10.90909091  6.81818182]
[ 8.54545455 12.72727273]


In [3]:
# Use the corner points of the rounded values and compute dot product to determine the minimum value 
x= [5., 11., 9.]
y= [17., 7., 13.]

obj= np.matrix([10000,8500])
obj= np.transpose(obj)
corners= np.matrix([x,y])
corners= np.transpose(corners)
result= np.dot(corners,obj)

# Check whether constraints are satisfied
constraints = np.array([[20,18], [50,30],[110,44]])
constraints_dot = np.dot(corners,constraints.T)

# Print corner points 
print("Corner points: \n",corners)

# Verify whether constraints are satisfied at each corner point
print("Value of each constraint at the corner points : \n",constraints_dot)

# For (11,7) the first constraint is not satisfied since 20(11) + 18(7) or 346 < 400
# So we pick the next set of corner points that produce the minimum
print ("Value of Objective Function at Each Corner Point", result)

print ("Number of P1 airplanes = {}".format(x[2]))
print ("Number of P2 airplanes = {}".format(y[2]))

Corner points: 
 [[ 5. 17.]
 [11.  7.]
 [ 9. 13.]]
Value of each constraint at the corner points : 
 [[ 406.  760. 1298.]
 [ 346.  760. 1518.]
 [ 414.  840. 1562.]]
Value of Objective Function at Each Corner Point [[194500.]
 [169500.]
 [200500.]]
Number of P1 airplanes = 9.0
Number of P2 airplanes = 13.0


In [4]:
constraints = np.array([[20,18], [50,30],[110,44]])

np.dot(corners,constraints.T).T

matrix([[ 406.,  346.,  414.],
        [ 760.,  760.,  840.],
        [1298., 1518., 1562.]])